[package]
name = "llm-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
image = "0.25.2"
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git", features = [
    "metal",
] }
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
